In [67]:
import numpy as np
import pprint

In [68]:
# ニューラルネットワークの構造
input_size = 3    # 入力層のニューロン数
hidden_size_1 = 4   # 隠れ層のニューロン数
output_size = 2   # 出力層のニューロン数

# 学習率
learning_rate = 0.01

In [69]:
# 重みの初期化
np.random.seed(0) # 再現性のためのシード値設定
W1 = np.random.randn(input_size, hidden_size_1)  # 入力層から隠れ層1への重み
b1 = np.zeros((1, hidden_size_1))                # 隠れ層1のバイアス
W2 = np.random.randn(hidden_size_1, output_size) # 隠れ層1から出力層への重み
b2 = np.zeros((1, output_size))                # 出力層のバイアス

pprint.pprint(W1)
pprint.pprint(b1)
pprint.pprint(W2)
pprint.pprint(b2)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])
array([[0., 0., 0., 0.]])
array([[ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])
array([[0., 0.]])


In [70]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# シグモイド関数の導関数
def sigmoid_derivative(x):
    return x * (1 - x)

# relu関数
def relu(x):
    return x * (0 < x)

In [71]:
def forward_propagation(X):
    # 隠れ層への入力
    test = np.dot(X, W1)
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    # 出力層への入力
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    
    return a1, a2

In [72]:
def backward_propagation(X, y, a1, a2):
    global W1, b1, W2, b2

    # 出力層の誤差
    output_error = y - a2
    output_delta = output_error * sigmoid_derivative(a2)

    # 隠れ層の誤差
    hidden_error = np.dot(output_delta, W2.T)
    hidden_delta = hidden_error * sigmoid_derivative(a1)

    # 重みとバイアスの更新
    W2 += learning_rate * np.dot(a1.T, output_delta)
    b2 += learning_rate * np.sum(output_delta, axis=0, keepdims=True)
    W1 += learning_rate * np.dot(X.T, hidden_delta)
    b1 += learning_rate * np.sum(hidden_delta, axis=0, keepdims=True)

In [73]:
def train(X, y, iterations):
    for i in range(iterations):
        # フォワードプロパゲーション
        a1, a2 = forward_propagation(X)
        
        # バックプロパゲーション
        backward_propagation(X, y, a1, a2)
        
        if (i+1) % 1000 == 0:
            loss = np.mean(np.square(y - a2))
            print(f'Iteration {i+1}, Loss: {loss}')

In [74]:
# トレーニングデータの例
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

# 学習を実行
train(X, y, 10000)


Iteration 1000, Loss: 0.24570491133209074
Iteration 2000, Loss: 0.2418688752346055
Iteration 3000, Loss: 0.23756111038779104
Iteration 4000, Loss: 0.23246377297320198
Iteration 5000, Loss: 0.22634825476644677
Iteration 6000, Loss: 0.2191330790829629
Iteration 7000, Loss: 0.21094254239219234
Iteration 8000, Loss: 0.20214036615841774
Iteration 9000, Loss: 0.19337892626082553
Iteration 10000, Loss: 0.18534242192228162
