In [15]:
import numpy as np
import pprint

In [16]:
# ニューラルネットワークの構造
input_size = 3    # 入力層のニューロン数
hidden_size_1 = 4   # 隠れ層のニューロン数
hidden_size_2 = 4   # 隠れ層のニューロン数
output_size = 2   # 出力層のニューロン数

# 学習率
learning_rate = 0.01

In [17]:
# 重みの初期化
np.random.seed(0) # 再現性のためのシード値設定
W1 = np.random.randn(input_size, hidden_size_1)  # 入力層から隠れ層1への重み
b1 = np.zeros((1, hidden_size_1))                # 隠れ層1のバイアス
W2 = np.random.randn(hidden_size_1, hidden_size_2) # 隠れ層1から隠れ層2への重み
b2 = np.zeros((1, hidden_size_2))                # 隠れ層2のバイアス
W3 = np.random.randn(hidden_size_2, output_size) # 隠れ層2から出力層への重み
b3 = np.zeros((1, output_size))                # 出力層のバイアス

pprint.pprint(W1)
pprint.pprint(b1)
pprint.pprint(W2)
pprint.pprint(b2)
pprint.pprint(W3)
pprint.pprint(b3)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])
array([[0., 0., 0., 0.]])
array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385]])
array([[0., 0., 0., 0.]])
array([[ 1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252],
       [-0.88778575, -1.98079647],
       [-0.34791215,  0.15634897]])
array([[0., 0.]])


In [18]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# シグモイド関数の導関数
def sigmoid_derivative(x):
    return x * (1 - x)

# relu関数
def relu(x):
    return x * (0 < x)

In [19]:
def forward_propagation(X):
    # 隠れ層1への入力
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    # 隠れ層2への入力
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # 出力層への入力
    z3 = np.dot(a2, W3) + b3
    a3 = sigmoid(z3)
    
    return a1, a2, a3

In [20]:
def backward_propagation(X, y, a1, a2, a3):
    global W1, b1, W2, b2, W3, b3

    # 出力層の誤差
    output_error = y - a3
    output_delta = output_error * sigmoid_derivative(a3)

    # 隠れ層の誤差
    hidden_2_error = np.dot(output_delta, W3.T)
    hidden_2_delta = hidden_2_error * sigmoid_derivative(a2)

    # 隠れ層の誤差
    hidden_1_error = np.dot(hidden_2_delta, W2.T)
    hidden_1_delta = hidden_1_error * sigmoid_derivative(a1)

    # 重みとバイアスの更新
    W3 += learning_rate * np.dot(a1.T, output_delta)
    b3 += learning_rate * np.sum(output_delta, axis=0, keepdims=True)
    W2 += learning_rate * np.dot(a1.T, hidden_2_delta)
    b2 += learning_rate * np.sum(hidden_2_delta, axis=0, keepdims=True)
    W1 += learning_rate * np.dot(X.T, hidden_1_delta)
    b1 += learning_rate * np.sum(hidden_1_delta, axis=0, keepdims=True)

In [21]:
def train(X, y, iterations):
    for i in range(iterations):
        # フォワードプロパゲーション
        a1, a2, a3 = forward_propagation(X)
        
        # バックプロパゲーション
        backward_propagation(X, y, a1, a2, a3)
        
        if (i+1) % 1000 == 0:
            loss = np.mean(np.square(y - a3))
            print(f'Iteration {i+1}, Loss: {loss}')

In [30]:
# トレーニングデータの例
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

# 学習を実行
train(X, y, 10000)

Iteration 1000, Loss: 1.8062941861995037e-05
